// <auto-generated />
namespace NotesApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class initial56 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial56));
        
        string IMigrationMetadata.Id
        {
            get { return "202001121837088_initial56"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
